import { DocumentFormSchema } from '@/@types/document'

export const defaultDocumentValues: DocumentFormSchema = {
    labName: '',
    location: '',
    department: [],
    mode: 'create',
    category: '',
    documentName: '',
    documentNo: '',
    header: '',
    footer: '',
    issuedNo: '',
    amendmentNo: '',
    copyNo: '',
    date: '',
    preparedByDate: '',
    time: '',
    preparedBy: '',
    quantityPrepared: '',
    approvedBy: '',
    issuedBy: '',
    issueDate: '',
    amendmentDate: '',
    effectiveDate: '',
    frequency: '',
    duration: '',
}
